#!/bin/sh
sudo pacman -Sy --noconfirm ansible &&
ansible localhost --module-name package --become --args name=ansible,git -v &&
ansible-pull -U https://github.com/voltamage/dotfiles.git -v &&
sudo pacman -Syyu &&
ansible-playbook ~/.ansible/pull/artixlinux/tasks/stage1.yml --ask-vault-pass -v &&
cd ~/dotfiles &&
git remote remove origin &&
git remote add origin git@github.com:voltamage/dotfiles.git &&
ansible-galaxy collection install kewlfft.aur -v &&
ansible-playbook ~/.ansible/pull/artixlinux/tasks/stage2.yml -v &&
mv ~/.ansible ~/.config/ansible &&
rm ~/.bash* &&
chezmoi apply &&
sudo chsh -s /usr/bin/zsh artix &&
Hyprland
