#!/bin/sh
sudo pacman -Sy --noconfirm ansible && ansible localhost --module-name package --become --args name=ansible,git && ansible-pull -U https://github.com/voltamage/dotfiles.git && cd ~/dotfiles && git remote remove origin && git tremote add origin git@github.com:voltamage/dotfiles.git && ansible-playbook ~/dotfiles/sshkey.yml --ask-vault-pass && ansible-playbook ~/dotfiles/stage2.yml
