#!/bin/sh
sudo pacman -Sy --noconfirm ansible glibc tmux &&
ansible localhost --module-name package --become --args name=ansible,git &&
ansible-galaxy collection install kewlfft.aur -vvv &&
tmux new-session -d -s install &&
tmux send-keys -t install "\
ansible-pull -U https://github.com/voltamage/dotfiles.git -vvv && \
ansible-playbook -vvv ~/.ansible/pull/artixlinux/tasks/list-packages.yml && \
ansible-playbook -vvv ~/.ansible/pull/artixlinux/tasks/list-aur.yml && \
ansible-playbook -vvv ~/.ansible/pull/artixlinux/tasks/list-manual.yml && \
ansible-playbook -vvv ~/.ansible/pull/artixlinux/tasks/post-install.yml && \
echo -e 'sudo passwd main\nexit\nlogin as main\nHyprland\n'" Enter
