#!/bin/sh
# Stop the reflector service that comes with the arch live environment
# This way we can run it with our own settings without mirrorlist conflicts
systemctl stop reflector.service

# Expand disk and ensure tmux is installed
mount -o remount,size=75% /run/archiso/cowspace
pacman -Sy --needed --noconfirm tmux

# Start tmux session install, update mirrorlist, system, and basic packages
# Download configs into a tmp directory, and start archinstall
# NOTE: Might want to create a dedicated directory in tmp to prevent file clash
tmux new-session -d -s install
tmux send-keys -t install "\
reflector --sort rate -c US -p https --delay 1 --save /etc/pacman.d/mirrorlist -x berkeley && \
pacman -Syu archinstall btop ranger --needed --noconfirm --ignore linux && \
cd /tmp && \
curl https://raw.githubusercontent.com/voltamage/dotfiles/main/files/user_configuration.json -O && \
curl https://raw.githubusercontent.com/voltamage/dotfiles/main/files/user_credentials.json -O && \
archinstall --config user_configuration.json --creds user_credentials.json" Enter
