#!/bin/sh
mount -o remount,size=4G /run/archiso/cowspace
pacman -Sy --noconfirm ansible booster btop git glibc neovim ranger tmux
yes | pacman -R mkinitcpio mkinitcpio-archiso mkinitcpio-busybox mkinitcpio-nfs-utils
if cd ~/dotfiles; then git pull; else git clone https://github.com/voltamage/dotfiles ~/dotfiles; fi
mkdir -p ~/.config/git
cp ~/dotfiles/chezmoi/dot_config/git/config ~/.config/git/config
tmux new-session -d -s install
tmux send-keys -t install "\
ansible-playbook -vvv ~/dotfiles/tasks/live.yml --ask-vault-pass && \
yes | pacman -Syyu" Enter
