- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Set pacman Color
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: Color
  
  - name: Set pacman ParallelDownloads
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#ParallelDownloads'
      line: ParallelDownloads = 12
  
  - name: Set pacman VerbosePkgLists
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#VerbosePkgLists'
      line: VerbosePkgLists

  - name: Enable multilib packages
    blockinfile:
      path: /etc/pacman.conf
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist

  - name: Synchronize package databases
    package:
      update_cache: true

  - name: Install base-devel, booster, chezmoi, and zsh
    package:
      name:
        - base-devel
        - booster
        - chezmoi
        - zsh

  - name: Remove mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-archiso
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
      state: absent
      force: true
  
  - name: Ensure the ansible user exists
    user:
      name: ansible
      create_home: yes

  - name: Allow the ansible user to run passwordless sudo
    lineinfile:
      path: /etc/sudoers.d/u_ansible
      line: 'ansible ALL=(ALL) NOPASSWD:ALL'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'
  
  - name: Ensure the main user exists
    user:
      name: main
      create_home: yes

  - name: Allow the main user to run passwordless sudo
    lineinfile:
      path: /etc/sudoers.d/u_main
      line: 'main ALL=(ALL) NOPASSWD:ALL'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'
  
  - name: Install ansible aur support for user ansible
    shell: ansible-galaxy collection install kewlfft.aur
    become: yes
    become_user: ansible
  
  - name: Install ansible aur support for user main
    shell: ansible-galaxy collection install kewlfft.aur
    become: yes
    become_user: main
  
  - name: Install ansible aur support for user root
    shell: ansible-galaxy collection install kewlfft.aur
    become: yes
    become_user: root
  
  - name: Git clone dotfiles
    shell: if cd ~/dotfiles; then git pull; else git clone https://github.com/voltamage/dotfiles ~/dotfiles; fi
    become: yes
    become_user: main
  
  - name: Fix dotfiles origin
    shell: cd ~/dotfiles && git remote remove origin && git remote add origin git@github.com:voltamage/dotfiles.git 
    become: yes
    become_user: main
  
  - name: Ensure chezmoi directory exists
    file:
      dest: /home/main/.config/chezmoi
      owner: main
      group: main
      state: directory
 
  - name: Configure chezmoi
    lineinfile:
      path: /home/main/.config/chezmoi/chezmoi.yaml
      line: 'sourceDir: ~/dotfiles/chezmoi'
      create: yes
      owner: main
      group: main
      mode: 0644

  - name: Configure dotfiles with chezmoi
    shell: chezmoi apply
    become: yes
    become_user: main
  
  - name: Ensure /etc/zsh directory exists
    file:
      dest: /etc/zsh
      owner: root
      group: root
      state: directory
      mode: 0755

  - name: Configure ZDOTDIR
    copy:
      dest: /etc/zsh/zshenv
      content: |
        export ZDOTDIR="$HOME"/.config/zsh
  
  - name: Ensure ~/.local/state/zsh directory exists
    file:
      dest: ~/.local/state/zsh
      owner: main
      group: main
      state: directory
      mode: 0755
    become: yes
    become_user: main
  
  - name: Ensure zsh history exists
    copy:
      content: ""
      dest: ~/.local/state/zsh/history
      force: no
      owner: main
      group: main
      mode: 0600
    become: yes
    become_user: main
  
  - name: Make user use zsh as the default shell
    shell: sudo chsh -s /usr/bin/zsh main
    become: yes
    become_user: ansible

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: main

  - name: Update system
    shell: yes | paru -Syyu
    become: yes
    become_user: main

  - name: Ensure installed packages
    package:
      name:
        - ansible
        - arch-wiki-docs
        - aria2
        - base-devel
        - bat
        - btop
        - chezmoi
        - eza
        - fd
        - fzf
        - gammastep
        - gcc
        - git
        - git-delta
        - glow
        - grim
        - kitty
        - lynx
        - man-db
        - mpv
        - ninja
        - nodejs
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - noto-fonts-extra
        - npm # NOTE: TSUpdate relies on this
        - onefetch
        - openssh
        - pacman-contrib
        - python-pillow # NOTE: this is required for ranger's kitty image preview
        - python-pynvim # NOTE: nvim checkhealth likes having this, added because python lsp
        - ranger
        - ripgrep
        - ripgrep-all
        - slurp
        - starship
        - sudo
        - tmux
        - tokei
        - tree-sitter-cli
        - ttf-jetbrains-mono-nerd
        - unzip # NOTE: mason depends on this
        - vivid # NOTE: LS_COLORS generator
        - wget # NOTE: mason depends on this
        - wikiman
        - wl-clipboard
        - xdg-desktop-portal-hyprland
        - yt-dlp
        - ytfzf
        - zoxide
        - zsh
  
  - name: Install aur packages
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        - ff2mpv-native-messaging-host-librewolf-git
        - hyprland-nvidia-git                       
        - librewolf-bin
        - librewolf-extension-dark-reader-bin
        - neovim-git
        # - nvtop-nosystemd-git
        - paru-bin
        - pfetch-rs-bin
        - rate-mirrors-bin
        - rofi-lbonn-wayland-only-git
        - swww
        # - timg
        # - tldr++
        - xdg-ninja-git
      state: present
    become: yes
    become_user: main

  - name: Install packages requiring manual intervention
    shell: yes | paru -S \
      neovim-symlinks \
      pigz-gzip-symlink \
    become: yes
    become_user: main

  - name: Install aur librewolf-extension-clearurls
    shell: cd ~/dotfiles/aur/librewolf-extension-clearurls && yes | makepkg -i
    become: yes
    become_user: main
  
  - name: Remove main user passwordless permissons
    shell: sudo rm /etc/sudoers.d/u_main
    become: yes
    become_user: ansible
  
  - name: Allow the main user to run passworded sudo
    lineinfile:
      path: /etc/sudoers.d/u_main
      line: 'main ALL=(ALL) ALL'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'
  
  - name: Remove main user lint
    shell: rm -rf ~/.cargo && rm ~/.bash*
    become: yes
    become_user: main
