- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Configure pacman
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: Color

  - name: Configure pacman
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#VerbosePkgLists'
      line: VerbosePkgLists
  
  - name: Configure pacman
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#ParallelDownloads'
      line: ParallelDownloads = 8
  
  - name: Install git
    package:
      name:
        - git
  
  - name: Ensure .ssh directory exists
    file:
      dest: ~/.ssh
      owner: artix
      group: artix
      state: directory
      mode: 0700 
  
  - name: Copy server private key
    copy:
      src: tasks/files/id_ed25519
      dest: ~/.ssh/id_ed25519
      decrypt: yes
      owner: artix
      group: artix
      mode: 0600 

  - name: Copy server public key
    copy:
      src: tasks/files/id_ed25519.pub
      dest: ~/.ssh/id_ed25519.pub
      decrypt: yes
      owner: artix
      group: artix
      mode: 0644 
  
  - name: Copy .gitconfig
    copy:
      src: tasks/files/.gitconfig
      dest: ~/.gitconfig
      decrypt: yes
      owner: artix
      group: artix
      mode: 0644 
  
  - name: Install packages
    package:
      name:
        - neovim
        - tmux
