- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
      name:
        - ansible
        - base-devel
        - git
        - neovim
        - tmux

  - name: Ensure .ssh directory exists
    file:
      dest: /home/artix/.ssh
      owner: artix
      group: artix
      state: directory
      mode: 0700 
  
  - name: Copy server private key
    copy:
      src: tasks/files/id_ed25519
      dest: /home/artix/.ssh/id_ed25519
      decrypt: yes
      owner: artix
      group: artix
      mode: 0400 

  - name: Copy server public key
    copy:
      src: tasks/files/id_ed25519.pub
      dest: /home/artix/.ssh/id_ed25519.pub
      decrypt: yes
      owner: artix
      group: artix
      mode: 0400 
