- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Initialize dotfiles repository
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/init-dotfiles.yml --ask-vault-pass
  
  - name: Install base-devel and booster
    package:
      name:
        - base-devel
        - booster

  - name: Create user ansible
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/user-ansible.yml

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: ansible
    
  - name: Install rate-mirrors
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        - rate-mirrors-bin
      state: present
    become: yes
    become_user: ansible
  
  - name: Configure mirrors
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/init-mirrors.yml
  
  - name: Apply dotfiles
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/apply-dotfiles.yml
  
  - name: Refresh mirrorlist
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/update-mirrors.yml
  
  - name: Removed mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
        - mkinitcpio-openswap
      state: absent
      force: true
  
  - name: Update system
    package:
      update_cache: true
      upgrade: true

  - name: Install packages
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/list-packages.yml
  
  - name: Configure shell
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/init-shell.yml
  
  - name: Remove bash shell related files
    command: rm /home/artix/.bash*
  
  - name: Move .ansible folder to XDG compliant folder in lieu of setting environment variables
    command: mv /home/artix/.ansible /home/artix/.config/ansible
