- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Configure pacman Color
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: Color

  - name: Configure pacman ParallelDownloads
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#ParallelDownloads'
      line: ParallelDownloads = 16
  
  - name: Configure pacman VerbosePkgLists
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#VerbosePkgLists'
      line: VerbosePkgLists
  
  - name: Install packages
    package:
      name:
        - ansible
        - curl
        - git
        - pacman-contrib
        - parallel
  
  - name: Retrieve latest Artix mirrorlist
    shell: curl https://gitea.artixlinux.org/packages/artix-mirrorlist/raw/branch/master/mirrorlist | tee /tmp/rankmirrors-artix

  - name: Rank Artix mirrors
    shell: rankmirrors -p /tmp/rankmirrors-artix | sudo tee /etc/pacman.d/mirrorlist
  
  - name: Add Universe repository and 32-bit support to pacman.conf
    blockinfile:
      path: /etc/pacman.conf
      block: |
        
        # For 32-bit packages
        [lib32]
        Include = /etc/pacman.d/mirrorlist
        
        # Artix repository containing artix-archlinux-support to enable Arch repos
        [universe]
        Server = https://mirror1.artixlinux.org/universe/$arch
    
  - name: Wipe current gpg and mirror dbs
    shell: sudo rm -rf /var/lib/pacman/sync && sudo rm -rf /etc/pacman.d/gnupg

  - name: Initialize and populate Artix keyring
    shell: sudo pacman-key --init && sudo pacman-key --populate

  - name: Add Arch Linux support for Artix
    package:
      name:
        - artix-archlinux-support
        - lib32-artix-archlinux-support
      update_cache: true
  
  - name: Add Arch repositories to pacman.conf
    blockinfile:
      path: /etc/pacman.conf
      block: |
        
        # For 32-bit packages
        [lib32]
        Include = /etc/pacman.d/mirrorlist
        
        # Arch Linux repos, community requires extra
        [extra]
        Include = /etc/pacman.d/mirrorlist-arch
        
        [multilib]
        Include = /etc/pacman.d/mirrorlist-arch
        
        # Artix repository containing artix-archlinux-support to enable Arch repos
        [universe]
        Server = https://mirror1.artixlinux.org/universe/$arch
  
  - name: Populate Arch keyring
    shell: sudo pacman-key --populate

  - name: Update system
    package:
      upgrade: true
      update_cache: true
