- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install packages
    package:
      name:
        - ansible
        - base-devel
        - git
        - neovim
        - tmux
