- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Initialize dotfiles repository
    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/init-dotfiles.yml --ask-vault-pass
  
  - name: Install base-devel and booster
    package:
      name:
        - base-devel
        - booster
  
  - name: ansible
  - import_playbook: tasks/user-ansible.yml

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: ansible
    
  - name: Install rate-mirrors
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        - rate-mirrors-bin
      state: present
    become: yes
    become_user: ansible
  
  - name: mirrors
  - import_playbook: tasks/init-mirrors.yml
  
  - name: dotfiles
  - import_playbook: tasks/init-dotfiles.yml
  
  - name: mirror update
  - import_playbook: tasks/update-mirrors.yml
  
  - name: Removed mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
        - mkinitcpio-openswap
      state: absent
      force: true
  
  - name: Update system
    package:
      update_cache: true
      upgrade: true
  
  - name: packages
  - import_playbook: tasks/list-packages.yml
 
  - name: shell
  - import_playbook: tasks/init-shell.yml
