- hosts: localhost
  connection: local
  become: true

  tasks:
#  - name: Setup ssh
#    shell: ansible-playbook /home/artix/.ansible/pull/artixlinux/tasks/stage1.yml --ask-vault-pass -v 

  - name: Ensure /etc/zsh directory exists
    file:
      dest: /etc/zsh
      owner: root
      group: root
      state: directory
      mode: 0755

  - name: Configure ZDOTDIR
    copy:
      dest: /etc/zsh/zshenv
      content: |
        export ZDOTDIR="$HOME"/.config/zsh
  
  - name: Ensure ~/.local/state/zsh directory exists
    file:
      dest: /home/artix/.local/state/zsh
      owner: artix
      group: artix
      state: directory
      mode: 0755
  
  - name: Ensure zsh history exists
    copy:
      content: ""
      dest: /home/artix/.local/state/zsh/history
      force: no
      owner: artix
      group: artix
      mode: 0600
  
  - name: Ensure chezmoi directory exists
    file:
      dest: /home/artix/.config/chezmoi
      owner: artix
      group: artix
      state: directory
      mode: 0755
  
  - name: Copy chezmoi.yaml
    copy:
      src: /home/artix/.ansible/pull/artixlinux/tasks/files/chezmoi.yaml
      dest: /home/artix/.config/chezmoi/chezmoi.yaml
      owner: artix
      group: artix
  
  - name: Git clone dotfiles
    git:
      repo: https://github.com/voltamage/dotfiles.git
      dest: /home/artix/dotfiles
    become: yes
    become_user: artix

  - name: Fix dotfiles origin
    shell: cd /home/artix/dotfiles && git remote remove origin && git remote add origin git@github.com:voltamage/dotfiles.git 

  - name: Configure pacman Color
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: Color

  - name: Configure pacman ParallelDownloads
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#ParallelDownloads'
      line: ParallelDownloads = 12
  
  - name: Configure pacman VerbosePkgLists
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#VerbosePkgLists'
      line: VerbosePkgLists

  - name: Install base-devel
    package:
      name:
        - base-devel
        - booster
  
  - name: Removed mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
        - mkinitcpio-openswap
      state: absent
      force: true
  
  - name: Ensure the aurbuild user exists
    user:
      name: aurbuild
      create_home: yes

  - name: Allow the aurbuild user to run 'sudo pacman' without a password
    lineinfile:
      path: /etc/sudoers.d/u_aurbuild
      line: 'aurbuild ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: aurbuild
    
  - name: Install rate-mirrors
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        - rate-mirrors-bin
      state: present
    become: yes
    become_user: aurbuild

  - name: Add Universe and lib32 repositories to pacman.conf
    blockinfile:
      path: /etc/pacman.conf
      block: |

        # For 32-bit packages
        [lib32]
        Include = /etc/pacman.d/mirrorlist
        
        # Artix repository containing artix-archlinux-support to enable Arch repos
        [universe]
        Server = https://mirror1.artixlinux.org/universe/$arch
  
  - name: Add Arch Linux support for Artix
    package:
      name:
        - artix-archlinux-support
        - lib32-artix-archlinux-support
      update_cache: true
  
  - name: Add Arch repositories to pacman.conf
    blockinfile:
      path: /etc/pacman.conf
      block: |
        
        # For 32-bit packages
        [lib32]
        Include = /etc/pacman.d/mirrorlist
        
        # Arch Linux repos, community requires extra
        [extra]
        Include = /etc/pacman.d/mirrorlist-arch
        
        [multilib]
        Include = /etc/pacman.d/mirrorlist-arch
        
        # Artix repository containing artix-archlinux-support to enable Arch repos
        [universe]
        Server = https://mirror1.artixlinux.org/universe/$arch
  
  - name: Update mirrorlist
    package:
      update_cache: true
  
  - name: Update and rank latest Arch mirrorlist
    shell: rate-mirrors artix | sed -e '/Server = https:/!d' | sudo tee /etc/pacman.d/mirrorlist
    become: yes
    become_user: artix
  
  - name: Update and rank latest Arch mirrorlist
    shell: rate-mirrors arch | sed -e '/Server = https:/!d' | sudo tee /etc/pacman.d/mirrorlist-arch
    become: yes
    become_user: artix
  
  - name: Delete stale mirror database
    shell: sudo rm -rf /var/lib/pacman/sync
  
  - name: Update system
    package:
      update_cache: true
      upgrade: true

#mv ~/.ansible ~/.config/ansible &&
#rm ~/.bash* &&
#chezmoi apply &&
#sudo chsh -s /usr/bin/zsh artix &&
