- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Initialize users
    shell: ansible-playbook -vvv /home/artix/.ansible/pull/artixlinux/tasks/init-users.yml

  - name: Initialize ssh
    shell: ansible-playbook -vvv /home/artix/.ansible/pull/artixlinux/tasks/init-ssh.yml --ask-vault-pass
  
  - name: Install base-devel and booster
    package:
      name:
        - base-devel
        - booster

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: main
    
  - name: Install rate-mirrors
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        - rate-mirrors-bin
      state: present
    become: yes
    become_user: main
  
  - name: Configure mirrors
    shell: ansible-playbook -vvv /home/artix/.ansible/pull/artixlinux/tasks/init-mirrors.yml
  
  - name: Refresh mirrorlist
    shell: ansible-playbook -vvv /home/artix/.ansible/pull/artixlinux/tasks/update-mirrors.yml
  
  - name: Removed mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
        - mkinitcpio-openswap
      state: absent
      force: true
  
#  - name: Update system
#    package:
#      update_cache: true
#      upgrade: true

  - name: Install packages
    shell: yes | paru -Syyu
    become: yes
    become_user: main
