- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install chezmoi
    package:
      name:
        - chezmoi
      state: present
      update_cache: true
  
  - name: Configure chezmoi
    lineinfile:
      path: /home/artix/.config/chezmoi/chezmoi.yaml
      line: 'sourceDir: ~/dotfiles/chezmoi'
      create: yes
      owner: artix
      group: artix
      mode: 0644
