- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update and rank latest Arch mirrorlist
    shell: rate-mirrors archarm | sudo tee /etc/pacman.d/mirrorlist
    become: yes
    become_user: ansible 
  
  - name: Delete stale mirror database
    shell: sudo rm -rf /var/lib/pacman/sync
  
  - name: Sync mirror database
    package:
      update_cache: true
