---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure packages required for playbook exist
      become: true
      become_user: main
      kewlfft.aur.aur:
        use: paru
        name:
          - hyprland-git
          - lib32-nvidia-utils
          - libva
          - libva-nvidia-driver-git
          - linux-lts-headers
          - linux-zen-headers
          - nvidia-dkms
          - nvidia-utils
          - qt5-wayland
          - qt5ct
          - sddm-git
          - sddm-sugar-dark

    - name: Configure nvidia modprobe
      blockinfile:
        path: /etc/modprobe.d/nvidia.conf
        backup: true
        create: true
        mode: 644
        block: |
          options nvidia-drm modeset=1

    - name: Add nvidia tweaks to bootloader
      lineinfile:
        backup: true
        path: /etc/default/grub
        regexp: "GRUB_CMDLINE_LINUX="
        line: 'GRUB_CMDLINE_LINUX="zswap.enabled=0 rootfstype=btrfs nvidia_drm.modeset=1 nvidia.NVreg_PreserveVideoMemoryAllocations=1"'

    - name: Add nvidia tweaks to mkinitcpio
      lineinfile:
        backup: true
        path: /etc/mkinitcpio.conf
        regexp: "MODULES="
        line: "MODULES=(btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm)"

    - name: Configure hyprland env vars
      become: true
      become_user: main
      blockinfile:
        path: ~/.config/hypr/hyprland.conf
        backup: true
        block: |
          # If you encounter crashes in Firefox, remove the line env = GBM_BACKEND,nvidia-drm
          # If you face problems with Discord windows not displaying or screen sharing not working in Zoom, remove or comment the line env = __GLX_VENDOR_LIBRARY_NAME,nvidia
          env = LIBVA_DRIVER_NAME,nvidia
          env = XDG_SESSION_TYPE,wayland
          env = GBM_BACKEND,nvidia-drm
          env = __GLX_VENDOR_LIBRARY_NAME,nvidia
          env = WLR_NO_HARDWARE_CURSORS,1

    - name: Enable and ensure stopped nvidia-suspend.service
      systemd:
        enabled: true
        state: stopped
        name: nvidia-suspend.service

    - name: Enable and ensure stopped nvidia-hibernate.service
      systemd:
        enabled: true
        state: stopped
        name: nvidia-hibernate.service

    - name: Enable and ensure stopped nvidia-resume.service
      systemd:
        enabled: true
        state: stopped
        name: nvidia-resume.service

    - name: Configure sddm
      blockinfile:
        path: /etc/sddm.conf.d/sddm.conf
        backup: true
        create: true
        mode: 644
        block: |
          [Theme]
          Current=sugar-dark

    - name: Enable and ensure started sddm.service
      systemd:
        enabled: true
        state: started
        name: sddm.service

    - name: Set Background
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^Background="
        line: 'Background="current"'

    - name: Set ScreenWidth
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^ScreenWidth="
        line: "ScreenWidth=1920"

    - name: Set ScreenHeight
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^ScreenHeight="
        line: "ScreenHeight=1080"

    - name: Set MainColor
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^MainColor="
        line: 'MainColor="#ddc7a1"'

    - name: Set AccentColor
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^AccentColor="
        line: 'AccentColor="#e78a4e"'

    - name: Set RoundCorners
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^RoundCorners="
        line: "RoundCorners=10"

    - name: Set Font
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^Font="
        line: 'Font="JetBrainsMono NFM Medium"'

    - name: Set DateFormat
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^DateFormat="
        line: 'DateFormat="ddd, MMM d"'

    - name: Set ForceHideCompletePassword
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^ForceHideCompletePassword="
        line: "ForceHideCompletePassword=true"

    - name: Set HeaderText
      lineinfile:
        path: /usr/share/sddm/themes/sugar-dark/theme.conf
        regexp: "^HeaderText="
        line: "HeaderText=󰣇"

    # - name: Set colors
    #   lineinfile:
    #     path: /usr/share/sddm/themes/sugar-dark/Main.qml
    #     regexp: '"#444"'
    #     line: '"#282828"'

    - name: ALWAYS CHANGED Rerun grub-mkconfig
      shell: grub-mkconfig -o /boot/grub/grub.cfg

    - name: ALWAYS CHANGED Regenerate initramfs with mkinitcpio
      shell: rm /boot/initramfs-* && mkinitcpio -P
