- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Ensure packages required for playbook exist
    become: true
    become_user: main
    kewlfft.aur.aur:
      extra_args: "--ignore linux --ignore linux-zen --ignore linux-lts"
      use: paru
      name:
        - hyprland-nvidia-git
        - linux-lts-headers
        - linux-zen-headers
        - nvidia-dkms

  - name: Add nvidia tweaks to bootloader
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: "GRUB_CMDLINE_LINUX="
      line: 'GRUB_CMDLINE_LINUX="zswap.enabled=0 rootfstype=btrfs nvidia_drm.modeset=1"'
  
  - name: Rerun grub-mkconfig
    shell: grub-mkconfig -o /boot/grub/grub.cfg
  
  - name: Add nvidia tweaks to mkinitcpio
    lineinfile:
      backup: true
      path: /etc/mkinitcpio.conf
      regexp: "MODULES="
      line: "MODULES=(btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm)"

  - name: Regenerate initramfs with mkinitcpio
    shell: mkinitcpio -p linux-zen && mkinitcpio -p linux-lts

  - name: Configure nvidia modprobe
    blockinfile:
      path: /etc/modprobe.d/nvidia.conf
      create: true
      mode: 0644
      block: |
        options nvidia-drm modeset=1
