- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Ensure packages required for playbook exist
    package:
      extra_args: "--ignore linux --ignore linux-zen"
      name:
        - chezmoi
        - git
        - zsh
  
  - name: Ensure the main user exists # how to set accompanying gid
    user:
      uid: 1000
      shell: /usr/bin/zsh
      name: main

  - name: Allow the main user to run passworded sudo
    blockinfile:
      path: /etc/sudoers.d/u_main
      create: true
      mode: 0644
      validate: 'visudo -cf %s'
      block: |
        main ALL=(ALL) ALL

  - name: Ensure the ansible user exists
    user:
      create_home: false
      name: ansible

  - name: Allow the ansible user to run passwordless sudo
    blockinfile:
      path: /etc/sudoers.d/u_ansible
      create: true
      mode: 0644
      validate: 'visudo -cf %s'
      block: |
        ansible ALL=(ALL) NOPASSWD:ALL

  - name: Git clone dotfiles
    become: true
    become_user: main
    git:
     # remote: git@github.com:voltamage/dotfiles.git
      force: false # this one is default but i wanted it to be verbose
      update: false
      dest: ~/dotfiles
      repo: https://github.com/voltamage/dotfiles

  - name: ALWAYS CHANGED Fix dotfiles origin
    become: true
    become_user: main
     # could do better, ansible module instead of shell
    shell:
      chdir: ~/dotfiles
      cmd: git remote remove origin && git remote add origin git@github.com:voltamage/dotfiles.git

  - name: Ensure .ssh directory exists
    become: true
    become_user: main
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: Copy server public key
    become: true
    become_user: main
    copy:
      force: false
      decrypt: true
      mode: 0644 
      src: ~/dotfiles/files/id_ed25519.pub
      dest: ~/.ssh/id_ed25519.pub
  
  - name: Copy server private key
    become: true
    become_user: main
    copy:
      force: false
      decrypt: true
      mode: 0600 
      src: ~/dotfiles/files/id_ed25519
      dest: ~/.ssh/id_ed25519
  
  - name: ALWAYS CHANGED Install ansible aur support for user main
    become: true
    become_user: main
    shell: ansible-galaxy collection install kewlfft.aur
  
  - name: ALWAYS CHANGED Install ansible aur support for user root
    shell: ansible-galaxy collection install kewlfft.aur

  - name: Ensure chezmoi directory exists
    become: true
    become_user: main
    file:
      path: ~/.config/chezmoi
      state: directory
      mode: 0755
 
  - name: Configure chezmoi
    become: true
    become_user: main
    blockinfile:
      path: ~/.config/chezmoi/chezmoi.yaml
      create: true
      mode: 0644
      block: |
        sourceDir: ~/dotfiles/chezmoi

  - name: ALWAYS CHANGED Configure dotfiles with chezmoi
    become: true
    become_user: main
    # Could probaby get it to be more idempotent with a if chezmoistate.boltdb check do nothing
    shell: chezmoi apply
