- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Ensure paru is installed
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: main
  
  - name: Install packages requiring manual intervention
    shell: yes | paru -S neovim-symlinks pigz-gzip-symlink
    become: yes
    become_user: main
