- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Ensure paru is installed
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: main
  
  - name: Install aur packages
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        - ff2mpv-native-messaging-host-librewolf-git
        - hyprland-nvidia-git                       
        - librewolf-bin
        - librewolf-extension-dark-reader-bin
        - neovim-git
        # - nvtop-nosystemd-git
        - paru-bin
        - pfetch-rs-bin
        - rate-mirrors-bin
        - rofi-lbonn-wayland-only-git
        - swww
        # - timg
        # - tldr++
        - xdg-ninja-git
      state: present
    become: yes
    become_user: main
