- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Ensure paru is installed
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: ansible
  
  - name: Install aur packages
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
#        - discordo-git -- needs networking
        - hyprland-nvidia-git                       
        - librewolf-bin
        - neovim-git
        - pfetch-rs-bin
#        - pigz-gzip-symlink --these need manual intervention for package replacement
#        - plzip-lzip-link
        - swww
        - tgpt-bin
        - timg
        - tldr++
        - xdg-ninja-git
      state: present
    become: yes
    become_user: ansible
