- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Ensure installed packages
    package:
      name:
        - ansible
        - arch-wiki-docs
        - aria2
        - base-devel
        - bat
        - chezmoi
        - fd
        - fzf
        - gcc
        - git
        - glow
        - htop
        - lynx
        - man-db
        - ninja
        - nodejs
        - npm # NOTE: TSUpdate relies on this
        - onefetch
        - openssh
        - openssl-1.1
        - pacman-contrib
        - python-pynvim # NOTE: nvim checkhealth likes having this, added because python lsp
        - ranger
        - ripgrep
        - ripgrep-all
        - rustup
        - starship
        - sudo
        - tmux
        - tokei
        - tree-sitter-cli
        - ttf-jetbrains-mono-nerd
        - unzip # NOTE: mason depends on this
        - wget # NOTE: mason depends on this
        - wikiman
        - yt-dlp
        - zoxide
        - zsh
