- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Ensure installed packages
    package:
      name:
        - ansible
        - arch-wiki-docs
        - aria2
        - artixnews
        - base-devel
        - bat
        - btop
        - chezmoi
        - eza
        - fd
        - fzf
        - gcc
        - git
        - glow
        - grim
        - kitty
        - lynx
        - man-db
        - mpv
        - ninja
        - nodejs
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - noto-fonts-extra
        - npm # NOTE: yamlls lsp relies on this
        - onefetch
        - openssh
        - pacman-contrib
        - python-pillow # NOTE: this is required for ranger's kitty image preview
        - ranger
        - ripgrep
        - ripgrep-all
        - slurp
        - starship
        - tmux
        - tokei
        - tree-sitter-cli
        - ttf-jetbrains-mono-nerd
        - unzip # NOTE: mason depends on this
        - wget # NOTE: mason depends on this
        - wikiman
        - wl-clipboard
        - xdg-desktop-portal-hyprland
        - yt-dlp
        - ytfzf
        - zoxide
        - zsh

  - name: Ensure removed packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
        - mkinitcpio-openswap
      state: absent
      force: true
