- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Ensure installed packages
    package:
      name:
        - arch-wiki-docs
        - aria2
        - artixnews
        - bat
        - btop
        - chezmoi
        - cloc
        - fd
        - fzf
        - grim
        - lynx
        - mpv
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - noto-fonts-extra
        - onefetch
        - pacman-contrib
        - ranger
        - ripgrep
        - ripgrep-all
        - slurp
        - tmux
        - ttf-jetbrains-mono-nerd
        - wezterm
        - wikiman
        - xdg-desktop-portal-hyprland
        - yt-dlp
        - ytfzf
        - zoxide
        - zsh

  - name: Ensure removed packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
        - mkinitcpio-openswap
      state: absent
      force: true
