- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Set pacman Color
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#Color'
      line: Color
  
  - name: Set pacman ParallelDownloads
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#ParallelDownloads'
      line: ParallelDownloads = 12
  
  - name: Set pacman VerbosePkgLists
    lineinfile:
      path: /etc/pacman.conf
      regexp: '^#VerbosePkgLists'
      line: VerbosePkgLists

  - name: Enable multilib packages
    blockinfile:
      path: /etc/pacman.conf
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist

  - name: Install base-devel and booster
    package:
      name:
        - base-devel
        - booster

  - name: Remove mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-archiso
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
      state: absent
      force: true
