- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Ensure .ssh directory exists
    file:
      dest: /home/artix/.ssh
      owner: artix
      group: artix
      state: directory
      mode: 0700 

  - name: Copy server public key
    copy:
      src: /home/artix/.ansible/pull/artixlinux/tasks/files/id_ed25519.pub
      dest: /home/artix/.ssh/id_ed25519.pub
      decrypt: yes
      owner: artix
      group: artix
      mode: 0644 
  
  - name: Copy server private key
    copy:
      src: /home/artix/.ansible/pull/artixlinux/tasks/files/id_ed25519
      dest: /home/artix/.ssh/id_ed25519
      decrypt: yes
      owner: artix
      group: artix
      mode: 0600 
  
  - name: Ensure .config/git directory exists
    file:
      dest: /home/artix/.config/git
      owner: artix
      group: artix
      state: directory
      mode: 0755 
  
  - name: Copy .gitconfig
    copy:
      src: /home/artix/.ansible/pull/artixlinux/tasks/files/.gitconfig
      dest: /home/artix/.config/git/config
      decrypt: yes
      owner: artix
      group: artix
  
