- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Install packages
    package:
      name:
        - arch-wiki-docs
        - aria2
        - artixnews
        - bat
        - btop
        - chezmoi
        - cloc
        - fd
        - fzf
        - lynx
        - mpv
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - noto-fonts-extra
        - onefetch
        - pacman-contrib
        - ranger
        - ripgrep
        - ripgrep-all
        - tmux
        - ttf-jetbrains-mono-nerd
        - wezterm
        - wikiman
        - xdg-desktop-portal-hyprland
        - yt-dlp
        - ytfzf
        - zoxide
        - zsh

  - name: Install aur packages
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
#        - discordo-git -- needs networking
        - hyprland-nvidia-nosystemd-git                       
        - librewolf-bin
        - neovim-nightly-bin
        - pfetch-rs-bin
        - pigz-gzip-symlink
        - plzip-lzip-link
        - swww
        - tgpt-bin
        - timg
        - tldr++
        - xdg-ninja-git
      state: present
    become: yes
    become_user: ansible
