- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Install packages
    package:
      name:
        - base-devel
        - chezmoi
        - fzf
        - htop
        - links
        - neovim
        - ranger
        - tmux
        - ttf-jetbrains-mono-nerd
  
  - name: Ensure the aurbuild user exists
    user:
      name: aurbuild
      create_home: yes

  - name: Allow the aurbuild user to run 'sudo pacman' without a password
    lineinfile:
      path: /etc/sudoers.d/u_aurbuild
      line: 'aurbuild ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: aurbuild
