- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Install packages
    package:
      name:
        - arch-wiki-docs
        - aria2
        - artixnews
        - base-devel
        - bat
        - btop
        - chezmoi
        - fzf
        - lynx
        - mpv
        - multilib-devel
        - onefetch
        - ranger
        - tmux
        - wezterm
        - wikiman
        - yt-dlp
        - ytfzf
        - zoxide
        - zsh
  
  - name: Ensure the aurbuild user exists
    user:
      name: aurbuild
      create_home: yes

  - name: Allow the aurbuild user to run 'sudo pacman' without a password
    lineinfile:
      path: /etc/sudoers.d/u_aurbuild
      line: 'aurbuild ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: aurbuild

  - name: Install aur packages
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
#        - discordo-git -- needs networking
        - hyprland-nvidia-nosystemd-git                       
        - librewolf-bin
        - neovim-nightly-bin
        - pfetch-rs-bin
        - swww
        - tgpt-bin
        - timg
        - waypaper-git
        - xdg-ninja-git
      state: present
    become: yes
    become_user: aurbuild
  
  - name: Ensure ~/.local/state/zsh directory exists
    file:
      dest: /home/artix/.local/state/zsh
      owner: artix
      group: artix
      state: directory
      mode: 0755
  
  - name: Ensure zsh history exists
    copy:
      content: ""
      dest: /home/artix/.local/state/zsh/history
      force: no
      owner: artix
      group: artix
      mode: 0600
