- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Install packages
    package:
      name:
        - arch-wiki-docs
        - base-devel
        - bat
        - chezmoi
        - fzf
        - htop
        - links
        - ranger
        - tmux
        - ttf-jetbrains-mono-nerd
        - wikiman
        - zoxide
        - zsh
  
  - name: Ensure the aurbuild user exists
    user:
      name: aurbuild
      create_home: yes

  - name: Allow the aurbuild user to run 'sudo pacman' without a password
    lineinfile:
      path: /etc/sudoers.d/u_aurbuild
      line: 'aurbuild ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install Paru
    kewlfft.aur.aur:
      name: paru-bin
      state: present
    become: yes
    become_user: aurbuild

  - name: Install aur packages
    kewlfft.aur.aur:
      name:
        - xdg-ninja-git
        - neovim-nightly-bin
      state: present
    become: yes
    become_user: aurbuild
  
  - name: Ensure ~/.local/state/zsh directory exists
    file:
      dest: /home/artix/.local/state/zsh
      owner: artix
      group: artix
      state: directory
      mode: 0755
  
  - name: Ensure zsh history exists
    copy:
      content: ""
      dest: /home/artix/.local/state/zsh/history
      force: no
      owner: artix
      group: artix
      mode: 0600
