- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Ensure Paru is installed
    kewlfft.aur.aur:
      name: paru-bin
      state: present

  - name: Set pacman Color
    lineinfile:
      path: /etc/pacman.conf
      regexp: "^#Color"
      line: "Color"
  
  - name: Set pacman ParallelDownloads
    lineinfile:
      path: /etc/pacman.conf
      regexp: "^#ParallelDownloads"
      line: "ParallelDownloads = 12"
  
  - name: Set pacman VerbosePkgLists
    lineinfile:
      path: /etc/pacman.conf
      regexp: "^#VerbosePkgLists"
      line: "VerbosePkgLists"

  - name: Enable multilib packages
    blockinfile:
      path: /etc/pacman.conf
      block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist

  - name: Synchronize package databases
    package:
      update_cache: true

# configured up till this point 
  - name: Install base-devel, booster, chezmoi, and zsh
    package:
      extra_args: "--ignore linux --ignore linux-zen"
      name:
        - base-devel
        - booster
        - chezmoi
        - zsh

  - name: Remove mkinitcpio packages
    package:
      name:
        - mkinitcpio
        - mkinitcpio-archiso
        - mkinitcpio-busybox
        - mkinitcpio-nfs-utils
      state: absent
      force: true
    become: yes
    become_user: ansible
  
  - name: Ensure chezmoi directory exists
    file:
      dest: ~/.config/chezmoi
      state: directory
    become: yes
    become_user: main
 
  - name: Configure chezmoi
    lineinfile:
      path: ~/.config/chezmoi/chezmoi.yaml
      line: 'sourceDir: ~/dotfiles/chezmoi'
      create: yes
      mode: 0644
    become: yes
    become_user: main

  - name: Configure dotfiles with chezmoi
    shell: chezmoi apply
    become: yes
    become_user: main
  
  - name: Ensure /etc/zsh directory exists
    file:
      dest: /etc/zsh
      owner: root
      group: root
      state: directory
      mode: 0755
    become: yes
    become_user: ansible

  - name: Configure ZDOTDIR
    blockinfile:
      path: /etc/zsh/zshenv
      block: |
        export ZDOTDIR="$HOME"/.config/zsh
      create: yes
      owner: root
      group: root
      mode: 0644
      validate: 'visudo -cf %s'
    become: yes
    become_user: ansible

  - name: Ensure ~/.local/state/zsh directory exists
    file:
      dest: ~/.local/state/zsh
      owner: main
      group: main
      state: directory
      mode: 0755
    become: yes
    become_user: main
  
  - name: Ensure zsh history exists
    copy:
      content: ""
      dest: ~/.local/state/zsh/history
      force: no
      owner: main
      group: main
      mode: 0600
    become: yes
    become_user: main
  
  - name: Make user use zsh as the default shell
    shell: sudo chsh -s /usr/bin/zsh main
    become: yes
    become_user: ansible

  - name: Allow the main user to run passwordless sudo
    blockinfile:
      path: /etc/sudoers.d/u_main
      block: |
        main ALL=(ALL) NOPASSWD:ALL
      create: yes
      owner: root
      group: root
      mode: 0644
      validate: 'visudo -cf %s'
    become: yes
    become_user: ansible

  - name: Update system
    shell: paru -Syu --noconfirm --ignore linux
    become: yes
    become_user: main

  - name: Ensure installed packages
    package:
      name:
        # - arch-wiki-docs
        # - gcc
        # - git-delta
        # - glow
        # - grim
        # - lynx
        # - pacman-contrib # NOTE: i dont remember what this is for
        # - python-pillow # NOTE: this is required for ranger's kitty image preview
        # - python-pynvim # NOTE: nvim checkhealth likes having this, added because python lsp
        # - ripgrep-all
        # - slurp
        # - vivid # NOTE: LS_COLORS generator
        # - wikiman
        # - ytfzf
        - ansible
        - aria2
        - base-devel
        - bat
        - booster
        - btop
        - chezmoi
        - eza
        - fd
        - fzf
        - gammastep
        - git
        - kitty
        - man-db
        - mpv
        - ninja
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - noto-fonts-extra
        - npm # NOTE: TSUpdate relies on this
        - onefetch
        - openssh
        - ranger
        - ripgrep
        - starship
        - sudo
        - tmux
        - tokei # NOTE: fast loc parser
        - tree-sitter-cli # tree-sitter wants this for health :TSInstallFromGrammar
        - ttf-jetbrains-mono-nerd
        - unzip # NOTE: mason depends on this
        - wget # NOTE: mason depends on this
        - wl-clipboard
        - xdg-desktop-portal-hyprland
        - yt-dlp
        - zoxide
        - zsh
 
  - name: Install aur packages
    kewlfft.aur.aur:
      use: paru
      extra_args: "-a"
      name:
        # - nvtop-nosystemd-git
        # - rofi-lbonn-wayland-only-git
        # - timg
        # - tldr++
        # - ff2mpv-native-messaging-host-librewolf-git
        - hyprland-nvidia-git
        - librewolf-bin
        - librewolf-extension-dark-reader-bin
        - neovim-git
        - paru-bin
        - pfetch-rs-bin
        - rate-mirrors-bin
        - swww
        - xdg-ninja-git
      state: present
    become: yes
    become_user: main

  - name: Install packages requiring manual intervention
    shell: paru -Sy --needed --noconfirm \
      neovim-symlinks \
      pigz-gzip-symlink \
    become: yes
    become_user: main

  - name: Install aur librewolf-extension-clearurls
    shell: cd ~/dotfiles/aur/librewolf-extension-clearurls && makepkg -i --needed --noconfirm
    become: yes
    become_user: main
  
  - name: Allow the main user to run passworded sudo
    blockinfile:
      path: /etc/sudoers.d/u_main
      block: |
        main ALL=(ALL) ALL
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'
