- hosts: localhost
  connection: local
  become: true

  tasks:  
  - name: Update and rank latest Artix mirrorlist
    #shell: rate-mirrors artix | sed -e '/Server = https:/!d' | sed -e '/berkeley/d' | sudo tee /etc/pacman.d/mirrorlist
    shell: rate-mirrors artix | sed -e '/Server = https:/!d' | sudo tee /etc/pacman.d/mirrorlist
    become: yes
    become_user: ansible
  
  - name: Update and rank latest Arch mirrorlist
    shell: rate-mirrors arch | sed -e '/Server = https:/!d' | sudo tee /etc/pacman.d/mirrorlist-arch
    become: yes
    become_user: ansible
  
  - name: Delete stale mirror database
    shell: sudo rm -rf /var/lib/pacman/sync
  
  - name: Sync mirror database
    package:
      update_cache: true
