alias c='chezmoi'
alias cat='bat -p'
alias cd='z'
alias cdi='zi'
alias cdif='chezmoi diff'
alias cgit='lazygit -p ~/dotfiles'
alias e='nvim'
alias en='nvim ~/.config/nvim/init.lua'
alias fd="$FZF_DEFAULT_COMMAND"
alias fetch='fastfetch -l small'
alias ff='fzf'
alias loc='tokei'
alias ls='eza -a -o --icons'
alias minecraft='prismlauncher -l 1.20.4'
alias ngit='lazygit -p ~/.config/nvim'
alias q='exit'
alias sf='source "$XDG_CONFIG_HOME"/fish/config.fish && source "$XDG_CONFIG_HOME"/fish/zshenv'
alias tree='eza -a -o --tree --icons'
alias twitch='wtwitch'
alias update-termuxfont='cp /usr/share/fonts/TTF/JetBrainsMonoNerdFontMono-Medium.ttf ~/dotfiles/chezmoi/private_dot_termux/font.ttf'

#fish_vi_key_bindings # this wipes out the custom bindings for some reason
bind \e\[B 'complete'
