alias c='chezmoi'
alias cat='bat -n'
alias cd='z'
alias cdi='zi'
alias cdif='chezmoi diff'
alias cgit='lazygit -p ~/dotfiles'
alias e='nvim'
alias en='nvim ~/.config/nvim/init.lua'
alias fd="$FZF_DEFAULT_COMMAND"
alias fetch='fastfetch -l small'
alias loc='tokei'
alias ls='eza -a -o --icons'
alias q='exit'
alias source-fish='source "$XDG_CONFIG_HOME"/fish/config.fish'
alias terraria='steam steam://rungameid/105600'
alias tree='eza -a -o --tree --icons'
alias update-termuxfont='cp /usr/share/fonts/TTF/JetBrainsMonoNerdFontMono-Medium.ttf ~/dotfiles/chezmoi/private_dot_termux/font.ttf'

#fish_vi_key_bindings # this wipes out the custom bindings for some reason
bind \e\[B 'complete'
